// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdMu4m8atS_HGJ_y3lNCu63UKbIvgw9D8',
    appId: '1:687170810324:web:6359c64e17ab76d706a641',
    messagingSenderId: '687170810324',
    projectId: 'aplikasirt-12cfb',
    authDomain: 'aplikasirt-12cfb.firebaseapp.com',
    databaseURL: 'https://aplikasirt-12cfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasirt-12cfb.firebasestorage.app',
    measurementId: 'G-7ZQJQ538R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZnUW5mbRzmXX0s-v8P19fLBz9RIzlzE',
    appId: '1:687170810324:android:9764792a157e2ba306a641',
    messagingSenderId: '687170810324',
    projectId: 'aplikasirt-12cfb',
    databaseURL: 'https://aplikasirt-12cfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasirt-12cfb.firebasestorage.app',
  );
}
